name: Get Pull Request Branch Information
inputs:
  issue-number:
    description: 'Issue Number of the Pull Request'
    required: true
    type: number
outputs:
  head-sha:
    description: Head SHA of the Pull Request Branch
    value: ${{ steps.get-head.outputs.sha }}
  head-ref:
    description: Head ref of the Pull Request Branch
    value: ${{ steps.get-head.outputs.ref }}
runs:
  using: composite
  steps:
    - name: Get PR Branch Information
      uses: actions/github-script@v6
      id: get-head
      with:
        script: |
          // Retrieve job statuses from GitHub API
          const pr = await github.request('GET /repos/{owner}/{repo}/pulls/{issue_number}', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ inputs.issue-number }}
          })

          const head = await pr.data.head;
          console.log(head)
          return head;
