name: Get Pull Request Branch Information
inputs:
  issue-number:
    description: 'Issue Number of the Pull Request'
    required: true
    type: number
outputs:
  head-sha:
    description: Head SHA of the Pull Request Branch
    value: ${{ steps.get-sha.outputs.result }}
runs:
  using: composite
  steps:
    - name: Get PR Branch Information
      uses: actions/github-script@v6
      id: get-sha
      with:
        result-encoding: string
        script: |
          // Retrieve job statuses from GitHub API
          const pr = await github.request('GET /repos/{owner}/{repo}/pulls/{issue_number}', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ inputs.issue-number }}
          })

          console.log(await pr.data)
          const head_sha = await pr.data.head.sha;
          console.log(head_sha)
          return head_sha
