name: Get Pull Request Branch Information
inputs:
  issue-number:
    description: 'Issue Number of the Pull Request'
    required: true
    type: number
outputs:
  base-ref:
    description: Base ref of the Pull Request Branch
    value: ${{ steps.get-head.outputs.base-ref }}
  base-sha:
    description: Base SHA of the Pull Request Branch
    value: ${{ steps.get-head.outputs.base-sha }}
  head-ref:
    description: Head ref of the Pull Request Branch
    value: ${{ steps.get-head.outputs.head-ref }}
  head-sha:
    description: Head SHA of the Pull Request Branch
    value: ${{ steps.get-head.outputs.head-sha }}
runs:
  using: composite
  steps:
    - name: Get PR Branch Information
      uses: actions/github-script@v6
      id: get-head
      with:
        script: |
          // Retrieve job statuses from GitHub API
          const pr = await github.request('GET /repos/{owner}/{repo}/pulls/{issue_number}', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ inputs.issue-number }}
          })

          core.setOutput('base-ref', pr.data.base.ref);
          core.setOutput('base-sha', pr.data.base.sha);
          core.setOutput('head-ref', pr.data.head.ref);
          core.setOutput('head-sha', pr.data.head.sha);
