name: Check Job Status
inputs:
  sha:
    description: 'SHA of the Git Commit to Check'
    required: true
    type: string
  jobs:
    description: 'Comma-separated list of Jobs to Check'
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: Check if Other Builds Are Complete
      uses: actions/github-script@v6
      with:
        script: |
          const jobs = "${{ inputs.jobs }}".split(',');
          const checkRuns = await github.request('GET /repos/{owner}/{repo}/commits/{ref}/check-runs', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "${{ inputs.sha }}"
          })
          var conclusions = {};
          for await (const cr of checkRuns.data.check_runs) {
            for(const job of jobs) {
              if (cr.name == job) {
                conclusions[job] = cr.conclusion
              }
            }
          }

          console.log(conclusions)
