name: on-comment

on:
  issue_comment:
    types:
      - created

permissions: write-all

jobs:
  dispatch-on-comment:
    runs-on: ubuntu-latest
    # Run this workflow only if someone comments 'deploy' on a Pull Request
    if: github.event.issue.pull_request && github.event.comment.body == 'deploy'
    steps:
      - uses: actions/checkout@v3
      # Issue comment is not directly linked to Pull Request Branch, use custom github-script based action
      - name: Get Pull Request Head SHA
        id: branch-info
        uses: ./.github/workflows/pr-branch-info
        with:
          issue-number: ${{ github.event.issue.number }}
      # Check if other builds are complete
      - name: Dispatch
        uses: actions/github-script@v6
        with:
          script: |
            const workflows = await github.request('GET /repos/{owner}/{repo}/actions/workflows', {
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            deployWorkflowId = workflows.data.workflows.find(i => i.name == 'deploy').id;
            console.log(deployWorkflowId)

            await github.request('GET /repos/{owner}/{repo}/actions/workflows/{workflow}/dispatches', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow: deployWorkflowId,
              ref: '${{ steps.branch-info.outputs.head-ref }}'
            });
