name: on-comment

on:
  issue_comment:
    types:
      - created

permissions:
  contents: read
  checks: read
  pull-requests: read

jobs:
  check-on-comment:
    runs-on: ubuntu-latest
    # Run this workflow only if someone comments 'deploy' on a Pull Request
    if: github.event.issue.pull_request && github.event.comment.body == 'deploy'
    steps:
      - uses: actions/checkout@v3
      # Issue comment is not directly linked to Pull Request Branch, use custom github-script based action
      - name: Get Pull Request Head SHA
        id: get-sha
        uses: ./.github/workflows/pr-head
        with:
          issue-number: ${{ github.event.issue.number }}
      # Check if other builds are complete
      - name: Check if Other Builds Are Complete
        uses: ./.github/workflows/check-status
        with:
          jobs: long-lasting,quickish
          sha: ${{ steps.get-sha.outputs.head-sha }}
      # Checkout again with head SHA
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-sha.outputs.head-sha }}