name: on-label

on:
  pull_request_target:
    types:
      - labeled
    branches:
      - main
      - dev

permissions:
  contents: read
  checks: read
  pull-requests: read

jobs:
  check-on-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Check if other builds are complete
      - name: Check if Other Builds Are Complete
        uses: ./.github/workflows/check-status
        with:
          jobs: long-lasting,quickish
          sha: ${{ github.event.pull_request.head.sha }}
