name: pr-open

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  quickish:
    runs-on: ubuntu-latest
    steps:
      - name: Semi Quick Action
        run: |
          sleep 2
  long-lasting:
    needs: quickish
    runs-on: ubuntu-latest
    steps:
      - name: Longer Action
        run: |
          sleep 5
